<a href="https://colab.research.google.com/github/michalis0/Business-Intelligence-and-Analytics/blob/master/labs/03%20-%20Pandas%20and%20Python/exercises/exercise_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Part 1

In [38]:
import pandas as pd
import polars as pl

## Question 1

 In the API walkthrough, we show you how to retrieve data from a website by making a request. For this exercise, we've already crawled the data and combined it into a dataset that includes a list of movies along with their IMDB ratings and other metadata.

You can load the data from the this URL: "https://media.githubusercontent.com/media/michalis0/Business-Intelligence-and-Analytics/refs/heads/master/data/imdb_movies.csv"

In [48]:
df_movies = pd.read_csv("https://media.githubusercontent.com/media/michalis0/Business-Intelligence-and-Analytics/refs/heads/master/data/imdb_movies.csv")
df_movies_pl = pl.read_csv("https://media.githubusercontent.com/media/michalis0/Business-Intelligence-and-Analytics/refs/heads/master/data/imdb_movies.csv", null_values=['NA', 'Not rated'])

## Question 2

Check the data by using the following functions:
* `.head(n)`(print the first n rows, `head()` by default returns the first 5 rows)
* `.tail(n)` (print the last n rows, `.tail()` by default returns the last 5 rows)
* `.columns` (column names)
* `.index` (raw identifier)
* `.dtypes` (column types)

In [50]:
# Beginning of the list
df_movies.head()
df_movies_pl.head()

shape: (5, 7)
┌───────────────────────────┬──────┬───────────────────────────┬──────────┬────────┬───────┬───────┐
│ Title                     ┆ Year ┆ Genres                    ┆ Duration ┆ Rating ┆ MPA   ┆ Votes │
│ ---                       ┆ ---  ┆ ---                       ┆ ---      ┆ ---    ┆ ---   ┆ ---   │
│ str                       ┆ i64  ┆ str                       ┆ str      ┆ f64    ┆ str   ┆ str   │
╞═══════════════════════════╪══════╪═══════════════════════════╪══════════╪════════╪═══════╪═══════╡
│ 1. American Sniper        ┆ 2014 ┆ ['Action', 'Biography',   ┆ 2h 13m   ┆ 7.3    ┆ R     ┆ 543K  │
│                           ┆      ┆ 'Drama…                   ┆          ┆        ┆       ┆       │
│ 2. The Hunger Games:      ┆ 2014 ┆ ['Dystopian Sci-Fi',      ┆ 2h 3m    ┆ 6.6    ┆ PG-13 ┆ 517K  │
│ Mockingja…                ┆      ┆ 'Action',…                ┆          ┆        ┆       ┆       │
│ 3. Guardians of the       ┆ 2014 ┆ ['Quest', 'Space Sci-Fi', ┆ 2h 1m    ┆ 8.0    ┆ PG-13 ┆ 1.3M  │
│ Galaxy                    ┆      ┆ 'Sup…                     ┆          ┆        ┆       ┆       │
│ 4. Captain America: The   ┆ 2014 ┆ ['Conspiracy Thriller',   ┆ 2h 16m   ┆ 7.7    ┆ PG-13 ┆ 920K  │
│ Winter…                   ┆      ┆ 'Polit…                   ┆          ┆        ┆       ┆       │
│ 5. The Lego Movie         ┆ 2014 ┆ ['Computer Animation',    ┆ 1h 40m   ┆ 7.7    ┆ PG    ┆ 397K  │
│                           ┆      ┆ 'Dystop…                  ┆          ┆        ┆       ┆       │
└───────────────────────────┴──────┴───────────────────────────┴──────────┴────────┴───────┴───────┘

In [51]:
# End of the list
df_movies.tail()
df_movies_pl.tail()

shape: (5, 7)
┌──────────────────────┬──────┬─────────────────────────────────┬──────────┬────────┬──────┬───────┐
│ Title                ┆ Year ┆ Genres                          ┆ Duration ┆ Rating ┆ MPA  ┆ Votes │
│ ---                  ┆ ---  ┆ ---                             ┆ ---      ┆ ---    ┆ ---  ┆ ---   │
│ str                  ┆ i64  ┆ str                             ┆ str      ┆ f64    ┆ str  ┆ str   │
╞══════════════════════╪══════╪═════════════════════════════════╪══════════╪════════╪══════╪═══════╡
│ 596. Vettaiyan       ┆ 2024 ┆ ['Cop Drama', 'One-Person Army… ┆ 2h 43m   ┆ 7.1    ┆ null ┆ 38K   │
│ 597. Nr. 24          ┆ 2024 ┆ ['Docudrama', 'Epic', 'Period … ┆ 1h 51m   ┆ 7.7    ┆ null ┆ 3.4K  │
│ 598. Parallel        ┆ 2024 ┆ ['Drama', 'Sci-Fi', 'Thriller'… ┆ 1h 28m   ┆ 5.3    ┆ null ┆ 1.7K  │
│ 599. Fight or Flight ┆ 2024 ┆ ['Action', 'Comedy']            ┆ 2h 46m   ┆ 7.0    ┆ null ┆ 117   │
│ 600. A Sacrifice     ┆ 2024 ┆ ['Drama', 'Horror', 'Mystery',… ┆ 1h 34m   ┆ 5.1    ┆ R    ┆ 4.3K  │
└──────────────────────┴──────┴─────────────────────────────────┴──────────┴────────┴──────┴───────┘

In [52]:
# Column names
df_movies.columns
df_movies_pl.columns

['Title', 'Year', 'Genres', 'Duration', 'Rating', 'MPA', 'Votes']

In [60]:
# Raw identifier
df_movies.index
df_movies_pl.with_row_index()["index"]

shape: (5_950,)
Series: 'index' [u32]
[
	0
	1
	2
	3
	4
	…
	5945
	5946
	5947
	5948
	5949
]

In [61]:
# Column types
df_movies.dtypes
df_movies_pl.dtypes

[String, Int64, String, String, Float64, String, String]

## Question 3

Remember that each column/attribute of our data may have different attribute types. Have a look at the following table to recall the different DataTypes in Pandas and Python (it is the same as in the walkthrough).

| Pandas dtype  | Python type  | NumPy type|Usage
| :--- | :--- | :--- | :--- |
| object| str or mixed | string_, unicode_, mixed types| Text or mixed numeric and non_numeric values |
| int 64| int| int_, int8, int16, int32, int64, uint8, uint18, uint32, uint64 | Integer numbers i.e. [1,2,3,...] |
| float64| float| float_, float15, float32, float64 | Floating point numbers (They contain decimal points) |
| bool| bool|bool_| True/False values|
| datetime64 | NA | datetime64[ns]     | Date and time values  |
| timedelta[ns] | NA  | NA| Differences between two datetime|
| category | NA| NA| Finite list of text values|

Use the following cells to convert each column to the required dtype:

In [64]:
# Convert MPA to category
df_movies['MPA'] = df_movies['MPA'].astype('category')
df_movies_pl = df_movies_pl.with_columns(pl.col('MPA').cast(pl.Categorical))

In [65]:
# Convert Rating to numeric
#help(pd.to_numeric)
df_movies['Rating'] = pd.to_numeric(df_movies['Rating'], errors='coerce')
df_movies_pl = df_movies_pl.with_columns(pl.col('Rating').cast(pl.Float64))

Now lets have a look at the new column types:

In [66]:
# New column types
df_movies.dtypes
df_movies_pl.dtypes

[String, Int64, String, String, Float64, Categorical, String]

# Part 2

## Question 4
The dataset contains some null values. Count the number of null values in each column using `.isnull().sum()`.

Then, remove all rows that contain **at least** one null value using `.dropna()`.

Print the shape of the dataframe before and after the cleaning process using `.shape`. How many rows were deleted?


#### Key Parameters for `.dropna()`:

- **axis**:
  - `0` (default) → Drops rows with NaN values.
  - `1` → Drops columns with NaN values.

- **how**:
  - `"any"` (default) → Drops a row if **any** value in the row is NaN.
  - `"all"` → Drops a row only if **all** values in the row are NaN.

- **inplace**:
  - `False` (default) → Returns a new DataFrame with NaN rows removed.
  - `True` → Modifies the original DataFrame in place.

**Solution:**

In [69]:
# Original shape
df_movies.shape
df_movies_pl.shape

(5950, 7)

In [70]:
# Get the original number of rows
df_movies.shape[0]
df_movies_pl.shape[0]

5950

In [71]:
# Count the number of null values in each column
df_movies.isnull().sum()
df_movies_pl.null_count()

shape: (1, 7)
┌───────┬──────┬────────┬──────────┬────────┬──────┬───────┐
│ Title ┆ Year ┆ Genres ┆ Duration ┆ Rating ┆ MPA  ┆ Votes │
│ ---   ┆ ---  ┆ ---    ┆ ---      ┆ ---    ┆ ---  ┆ ---   │
│ u32   ┆ u32  ┆ u32    ┆ u32      ┆ u32    ┆ u32  ┆ u32   │
╞═══════╪══════╪════════╪══════════╪════════╪══════╪═══════╡
│ 0     ┆ 0    ┆ 0      ┆ 26       ┆ 36     ┆ 1364 ┆ 38    │
└───────┴──────┴────────┴──────────┴────────┴──────┴───────┘

In [73]:
# Drop rows with null values
df_movies_drop = df_movies.copy().dropna()
df_movies_drop_pl = df_movies_pl.drop_nulls()

In [74]:
# Print shape of data after dropping null values
df_movies_drop.shape
df_movies_drop_pl.shape

(4585, 7)

In [75]:
# Check the number of rows after dropping
df_movies_drop.shape[0]
df_movies_drop_pl.shape[0]

4585

<h2>Important: This question answers the Moodle quiz question 1. </h2>

In [76]:
# Print the percentage of rows removed from the dataset as a result of the cleaning
1- df_movies_drop.shape[0] / df_movies.shape[0]
1- df_movies_drop_pl.shape[0] / df_movies_pl.shape[0]

0.22941176470588232

## Question 5

We will now apply some selections/filters on the dataframe to get some insights:
- Display the statistics of the ratings (hint: use `describe()`).
- Find the average rating of movies per year (hint: use `groupby()` and `mean()`).
- Print the top 10 movies with lowest ratings in 2022 (hint: filter movies that released in 2022 and use `sort_values()`).
- [Optional] Find the average rating of action movies per year (hint: filter movies that contain 'Action' in their Genres, use `groupby()` and `mean()`).

**Solution**:

In [80]:
# Display the statistics of the ratings
df_movies_drop['Rating'].describe()
df_movies_drop_pl['Rating'].describe()

shape: (9, 2)
┌────────────┬──────────┐
│ statistic  ┆ value    │
│ ---        ┆ ---      │
│ str        ┆ f64      │
╞════════════╪══════════╡
│ count      ┆ 4585.0   │
│ null_count ┆ 0.0      │
│ mean       ┆ 6.32831  │
│ std        ┆ 1.016548 │
│ min        ┆ 1.2      │
│ 25%        ┆ 5.7      │
│ 50%        ┆ 6.4      │
│ 75%        ┆ 7.0      │
│ max        ┆ 9.0      │
└────────────┴──────────┘

In [85]:
# Average rating per year
df_movies_drop.groupby('Year')['Rating'].mean()
df_movies_drop_pl.group_by('Year').agg(pl.col('Rating').mean())

shape: (11, 2)
┌──────┬──────────┐
│ Year ┆ Rating   │
│ ---  ┆ ---      │
│ i64  ┆ f64      │
╞══════╪══════════╡
│ 2014 ┆ 6.493528 │
│ 2015 ┆ 6.493777 │
│ 2016 ┆ 6.485287 │
│ 2017 ┆ 6.409111 │
│ 2018 ┆ 6.459406 │
│ …    ┆ …        │
│ 2021 ┆ 6.222849 │
│ 2020 ┆ 5.941328 │
│ 2022 ┆ 6.188861 │
│ 2023 ┆ 6.327493 │
│ 2024 ┆ 6.167751 │
└──────┴──────────┘

<h2> Important: This question answers the Moodle quiz question 2. <h2>

In [86]:
# Top 10 movies with the lowest rating in 2022
df_movies_drop[df_movies_drop['Year'] == 2022].sort_values('Rating').head(10)
df_movies_drop_pl.filter(pl.col('Year') == 2022).sort('Rating').head()

shape: (5, 7)
┌───────────────────────────────┬──────┬───────────────────────┬──────────┬────────┬───────┬───────┐
│ Title                         ┆ Year ┆ Genres                ┆ Duration ┆ Rating ┆ MPA   ┆ Votes │
│ ---                           ┆ ---  ┆ ---                   ┆ ---      ┆ ---    ┆ ---   ┆ ---   │
│ str                           ┆ i64  ┆ str                   ┆ str      ┆ f64    ┆ cat   ┆ str   │
╞═══════════════════════════════╪══════╪═══════════════════════╪══════════╪════════╪═══════╪═══════╡
│ 119. Jeepers Creepers: Reborn ┆ 2022 ┆ ['Horror', 'Mystery', ┆ 1h 28m   ┆ 2.6    ┆ R     ┆ 16K   │
│                               ┆      ┆ 'Thrille…             ┆          ┆        ┆       ┆       │
│ 454. 365 Days: This Day       ┆ 2022 ┆ ['Steamy Romance',    ┆ 1h 51m   ┆ 2.7    ┆ TV-MA ┆ 26K   │
│                               ┆      ┆ 'Drama', 'R…          ┆          ┆        ┆       ┆       │
│ 332. Nikamma                  ┆ 2022 ┆ ['Action', 'Comedy',  ┆ 2h 32m   ┆ 2.8    ┆ PG-13 ┆ 1.8K  │
│                               ┆      ┆ 'Drama']              ┆          ┆        ┆       ┆       │
│ 452. The Next 365 Days        ┆ 2022 ┆ ['Steamy Romance',    ┆ 1h 52m   ┆ 2.9    ┆ TV-MA ┆ 11K   │
│                               ┆      ┆ 'Drama', 'R…          ┆          ┆        ┆       ┆       │
│ 354. Good Mourning            ┆ 2022 ┆ ['Stoner Comedy',     ┆ 1h 33m   ┆ 3.1    ┆ R     ┆ 2.7K  │
│                               ┆      ┆ 'Comedy']             ┆          ┆        ┆       ┆       │
└───────────────────────────────┴──────┴───────────────────────┴──────────┴────────┴───────┴───────┘

In [88]:
# Average rating of action movies per year
# Filter movies which Genres list contains 'Action'
df_movies_drop[df_movies_drop['Genres'].str.contains('Action')].head()
df_movies_drop_pl.filter(pl.col('Genres').str.contains('Action')).head()

# Group by year and calculate the average rating
df_movies_drop[df_movies_drop['Genres'].str.contains('Action')].groupby('Year')['Rating'].mean()
df_movies_drop_pl.filter(pl.col('Genres').str.contains('Action')).group_by('Year').agg(pl.col('Rating').mean())

shape: (11, 2)
┌──────┬──────────┐
│ Year ┆ Rating   │
│ ---  ┆ ---      │
│ i64  ┆ f64      │
╞══════╪══════════╡
│ 2018 ┆ 6.291398 │
│ 2024 ┆ 5.885106 │
│ 2015 ┆ 6.240625 │
│ 2017 ┆ 6.397368 │
│ 2021 ┆ 6.071053 │
│ …    ┆ …        │
│ 2020 ┆ 5.815294 │
│ 2023 ┆ 6.207059 │
│ 2022 ┆ 6.179487 │
│ 2019 ┆ 6.195455 │
│ 2014 ┆ 6.35102  │
└──────┴──────────┘